import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "sonner";
import { ProviderCompose } from "./_providers/provider-compose";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "MyCuteApp",
  description: "Generated by create next fastly"
};

export default function RootLayout({
                                     children
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
    <body
      className={`${montserrat.className} flex min-h-screen flex-col bg-background antialiased`}
    >
    <ProviderCompose>{children}</ProviderCompose>
    <Toaster />
    </body>
    </html>
  );
}
